apiVersion: v1
kind: Service
metadata:
  name: golang-app
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    targetPort: {{ .Values.app.servicePort }}
  selector:
    app: golang-app
  type: LoadBalancer