apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  dbPassword: {{ .Values.postgres.dbPassword | b64enc | quote }}
  dbUser: {{ .Values.postgres.dbUser | b64enc | quote }}