namespace: social-net

postgres:
  image: postgis/postgis
  tag: 17-3.5
  dbName: social
  dbUser: social
  dbPassword: social
  storage: 10Gi

redis:
  image: redis
  tag: alpine

app:
  image: van4ik/social-net
  tag: 1.0.4
  replicaCount: 5
  servicePort: 80

ingress:
  enabled: true
  className: "nginx"
  host: arch.homework
